//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_OSAGO_Luzin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policies
    {
        public int PolicyID { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string LicenseSeriesNumber { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual InsuranceCompanies InsuranceCompanies { get; set; }
    }
}
